[project]
name = "projet2-perso"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "seaborn>=0.13.2",
    "streamlit>=1.51.0",
    "streamlit-option-menu>=0.4.0",
]
